# config.yml

autodoc:
  username: ""
  password: ""
  url: "https://www.autodoc.ru"
  auth_url: "https://auth.autodoc.ru/token"
  api_url: "https://webapi.autodoc.ru"

telegram:
  token: ""
  chat_id: 0

database:
  url: ""
  user: ""
  password: ""
  database: ""