# config.yml

autodoc:
  username: ""
  password: ""
  url: "https://www.autodoc.ru/"
  auth_url: "https://auth.autodoc.ru/token"
  partnumbers_url: "https://webapi.autodoc.ru/api/spareparts/511/%s/2?isrecross=false"

telegram:
  token: ""
  chat_id: 0

database:
  url: ""
  user: ""
  password: ""
  database: ""